<?php

use App\Enums\ProductUnit;

return [
    'rice' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Bag->value, ProductUnit::Sack->value, ProductUnit::Pack->value],
    'corn-flour' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Bag->value, ProductUnit::Sack->value, ProductUnit::Pack->value],
    'grains' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Bag->value, ProductUnit::Sack->value, ProductUnit::Pack->value],
    'leafy-greens' => [ProductUnit::Bundle->value, ProductUnit::Kilogram->value, ProductUnit::Piece->value, ProductUnit::Gram->value],
    'fresh-aromatics' => [ProductUnit::Bundle->value, ProductUnit::Kilogram->value, ProductUnit::Piece->value, ProductUnit::Gram->value],
    'root-crops' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value, ProductUnit::Bundle->value, ProductUnit::Bag->value],
    'fruit-vegetables' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value, ProductUnit::Bundle->value, ProductUnit::Bag->value],
    'vegetables' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value, ProductUnit::Bundle->value, ProductUnit::Bag->value],
    'fruits' => [ProductUnit::Kilogram->value, ProductUnit::Piece->value, ProductUnit::Gram->value, ProductUnit::Dozen->value, ProductUnit::Bag->value],
    'tropical-fruits' => [ProductUnit::Kilogram->value, ProductUnit::Piece->value, ProductUnit::Gram->value, ProductUnit::Dozen->value, ProductUnit::Bag->value],
    'citrus-fruits' => [ProductUnit::Kilogram->value, ProductUnit::Piece->value, ProductUnit::Gram->value, ProductUnit::Dozen->value, ProductUnit::Bag->value],
    'bananas-plantains' => [ProductUnit::Bundle->value, ProductUnit::Piece->value, ProductUnit::Kilogram->value, ProductUnit::Dozen->value],
    'fresh-fish' => [ProductUnit::Kilogram->value, ProductUnit::Piece->value, ProductUnit::Gram->value],
    'seafood' => [ProductUnit::Kilogram->value, ProductUnit::Piece->value, ProductUnit::Gram->value],
    'shellfish' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value],
    'crustaceans' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value],
    'pork' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value],
    'beef' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value],
    'chicken' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value],
    'meat-poultry' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Piece->value],
    'eggs' => [ProductUnit::Tray->value, ProductUnit::Piece->value, ProductUnit::Dozen->value],
    'dairy-eggs' => [ProductUnit::Tray->value, ProductUnit::Piece->value, ProductUnit::Dozen->value],
    'milk-dairy' => [ProductUnit::Bottle->value, ProductUnit::Liter->value, ProductUnit::Milliliter->value, ProductUnit::Pack->value, ProductUnit::Box->value],
    'cooking-oils' => [ProductUnit::Bottle->value, ProductUnit::Liter->value, ProductUnit::Milliliter->value, ProductUnit::Can->value],
    'condiments-sauces' => [ProductUnit::Bottle->value, ProductUnit::Pack->value, ProductUnit::Can->value, ProductUnit::Liter->value],
    'spices-condiments-oils' => [ProductUnit::Pack->value, ProductUnit::Piece->value, ProductUnit::Bundle->value, ProductUnit::Bottle->value],
    'dried-fish' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Pack->value, ProductUnit::Bundle->value, ProductUnit::Piece->value],
    'dried-salted-goods' => [ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Pack->value, ProductUnit::Bundle->value, ProductUnit::Piece->value],
    'smoked-fermented-goods' => [ProductUnit::Piece->value, ProductUnit::Kilogram->value, ProductUnit::Pack->value, ProductUnit::Bottle->value, ProductUnit::Can->value],
    'kakanin-native-sweets' => [ProductUnit::Bilao->value, ProductUnit::Piece->value, ProductUnit::Tray->value, ProductUnit::Pack->value, ProductUnit::Box->value],
    'steamed-kakanin' => [ProductUnit::Bilao->value, ProductUnit::Piece->value, ProductUnit::Tray->value, ProductUnit::Pack->value, ProductUnit::Box->value],
    'native-delicacies' => [ProductUnit::Bilao->value, ProductUnit::Piece->value, ProductUnit::Tray->value, ProductUnit::Pack->value, ProductUnit::Box->value],
    'frozen-processed-goods' => [ProductUnit::Pack->value, ProductUnit::Piece->value, ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Box->value],
    'frozen-ready-to-cook' => [ProductUnit::Pack->value, ProductUnit::Piece->value, ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Box->value],
    'cured-meats' => [ProductUnit::Pack->value, ProductUnit::Piece->value, ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Box->value],
    'default' => [ProductUnit::Piece->value, ProductUnit::Kilogram->value, ProductUnit::Gram->value, ProductUnit::Bundle->value, ProductUnit::Pack->value],
];
